### PR TITLE
fix: remove --legacy-output to resolve build errors

### PR DESCRIPTION
**Pull request by CaduZulian**

### CODE REVIEW

**Comment by CaduZulian** [comment]
Hello,

I use the react-select-async-paginate library and I noticed that some errors started to happen a few weeks ago. Basically, my unit tests broke and I was getting an error in the terminal (ERR_REQUIRE_ESM). I analyzed it in depth and arrived at this repository.

From what I was able to analyze, this error is happening because in the last update of this library, the engine that generates the build was changed (from vite to tsup), and in this change, a configuration was added that does not generate .cjs files in the dist, the which causes the error, as packages with "type": "module" need this .cjs file.

Just by removing the --legacy-output flag the error has already disappeared, so I created this PR to be analyzed and if this really solves the problem, it should be adopted.

**Comment by vtaits** [comment]
Hello. There was the bug with resolving `.mjs`/`.cjs` in `webpack`, so I added `--legacy-output`. I hope it's already fixed :smile: 

Change please `main`, `module` and `exports` sections if file extensions are to change.

**Comment by CaduZulian** [comment]
Oops, I ended up letting these points pass, I don't have that much experience in this part of libraries.

Thank you for analyzing my PR, in the tests I carried out the problem disappeared, but if possible, also test to ensure that new problems have not appeared hahaha

**Comment by vtaits** [comment]
Published in version `0.1.3`. Thank you :+1:

**Pull request merged**
